server:
  port: 8001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: myshops-provider-biz
  cloud:
    nacos:
      discovery:
        #注册中心地址
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-init-sql: SELECT 1
mybatis:
  type-aliases-package: com.li.myshops.domain
  mapper-locations: classpath:/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"